[package]
name = "search"
version = "0.4.0"
edition = "2021"
homepage = "https://github.com/reduf/search"
repository = "https://github.com/reduf/search"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
anyhow = "1.0.66"
cfg-if = "1.0.0"
clipboard = "0.5"
glium = { version = "0.32.1", default-features = true }
grep = "0.2"
ignore = "0.4"
image = "0.24"
imgui = { version = "0.9.0", features = ["tables-api"] }
imgui-glium-renderer = "0.9.0"
imgui-winit-support = "0.9.0"
indoc = "1.0"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
